### ISSUE TITLE
MQTT connection issues

### ISSUE THREAD

**Issue by mmajb** [SamsungARTIK/artik-sdk#28]
Hi,
I'm using an Artik 530s with Ubuntu and Artik SDK version 1.8-0. I'm facing two issues right now while using the Mqtt class of the Artik SDK:

1. The Mqtt connection with a cloud device for receiving actions from the device seems to close if there is no action sent from the device for 5 minutes. There is no warning issued or disconnect callback called. The program just becomes unresponsive to any actions sent from the Samsung Artik phone app.

2. With SSL verification level set to ARTIK_SSL_VERIFY_REQUIRED, the MQTT connection often fails when there are other modules like Http, Cloud being used in parallel. For example, if I use the connect function of the Mqtt class to create an MQTT connection and before the connection is made if I make an HTTP request to one of the services running on the Artik itself (like the Edge Node manager) or try to send a message to a cloud device using the Cloud class, I get the MQTT disconnection callback most of the times. With SSL verification level set to ARTIK_SSL_VERIFY_NONE however, the system works smoothly.

Can someone please help with these issues? Thanks.

Regards,
Ahsan

**Comment by glemercier** [comment]
Hi Ahsan,

Thanks for the report, let us try to reproduce these issues on our side and get back to you. Also note that SDK 1.8.1 has been released and contains numerous bug fixes. I would suggest you migrate to this newer version, no changes have been made on the API therefore it should be straight-forward to port your application.

I'll keep you posted. Thanks,

Greg

**Comment by mmajb** [comment]
Hi glemercier,

Thanks for your response. How can I get the new SDK? 

Ahsan

**Comment by glemercier** [comment]
On your board, you can do

`apt-get upgrade`

Or from source: https://github.com/SamsungARTIK/artik-sdk/tree/1.8.1

**Comment by glemercier** [comment]
Hi Ahsan,

I have some news about the issues you reported:

1. This is an issue in the SDK indeed. The keepalive mechanism of the underlying mosquitto library was not properly handled. This patch https://github.com/SamsungARTIK/artik-sdk/commit/dd08850373ae074ceb0fa094e9d8998d501eb9a5 fixes the issue. It will be tested internally and will be part of the next 1.8.2 release.

2. I could observe the same issue, and figured out it was due to OpenSSL whose global structures were re-initialized by the CURL when doing the HTTP call during the MQTT TLS handshake. Unfortunately there is nothing we can do until upgrade to OpenSSL 1.1 which is supposed to address this well known issue better. In the meantime I can only advise you to take precautions in your application code to avoid these situations.

I did some more testing and noticed that you can do HTTP requests while the MQTT connection is on, you just need to avoid doing it while some TLS stuff is going on (handshake, publishing messages, receiving subscribed messages, etc...). For instance instead of doing the HTTP request right after the MQTT connect function, you should do it in the MQTT "on_connect" callback, at this point the handshake is over and you should be fine making the request. I understand this is not ideal situation but there is not much we can do at the SDK level since OpenSSL initialization is handled by the underlying libraries (mosquitto and curl) and we would rather not modify these "standard" libraries. Another solution would be to make the HTTP request in a different process than you MQTT connection, again I understand it's far from being ideal.

I hope this clears you concerns and allow you to move forward with your project, feel free to comment is anything is still unclear to you.

Greg

**Comment by mmajb** [comment]
Hi glemercier,

Thanks for the update. When is the version 1.8.2 going to be released? I'm asking this because I haven't been able to build the source code. I run the 

`builddeb.sh armhf`

command on the Artik 530s but it always fails with this error:

`dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_SYSROOT= -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TEST=1 returned exit code 1
debian/rules:15: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory '/root/artik-sdk/build-armhf/package/src'
debian/rules:12: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2`

Can you help with that? Thanks.

Ahsan

**Comment by glemercier** [comment]
It's weird, I tried to build a package from source exactly how you did it above and it went successfully. What system image do you have installed on your board? You can figure it out with the following command:
`$ cat /etc/artik_release`

**Comment by mmajb** [comment]
That's the response:
`OFFICIAL_VERSION=A530s_os_3.3.0
BUILD_VERSION=0530GS0F-44U-DD60
BUILD_DATE=20180406.000000
BUILD_UBOOT=U-Boot 2016.01-0530GS0F-44U-DD60
BUILD_KERNEL=4.4.113-0530GS0F-44U-DD60
MODEL=ARTIK530S
WIFI_FW=SD8977-16.68.1.p218
BT_FW=SD8977-16.26.1.p218
ZIGBEE_FW=5.7.4 GA build 99 xNCP 0x8
SE_FW=f3010200`

**Comment by glemercier** [comment]
You probably miss some development packages. I tried on a clean image freshly flashed and was able to build it as follows:

```
$ cat /etc/artik_release
OFFICIAL_VERSION=A530s_os_3.3.0
BUILD_VERSION=0530GS0F-44U-DD60
BUILD_DATE=20180406.000000
BUILD_UBOOT=U-Boot 2016.01-0530GS0F-44U-DD60
BUILD_KERNEL=4.4.113-0530GS0F-44U-DD60
MODEL=ARTIK530S
WIFI_FW=SD8977-16.68.1.p218
BT_FW=SD8977-16.26.1.p218
ZIGBEE_FW=5.7.4 GA build 99 xNCP 0x8
SE_FW=f3010200
$ apt update
$ apt install debhelper git cmake build-essential libwebsockets-dev libglib2.0-dev libgstreamer1.0-dev libdbus-1-dev libcurl4-openssl-dev libssl-dev libmosquitto-dev libcunit1-dev libzigbee-dev wakaama-client-dev
$ git clone https://github.com/SamsungARTIK/artik-sdk.git
$ cd artik-sdk
$ ./builddeb.sh armhf
```

**Comment by mmajb** [comment]
Yes the build process did go further from that point but now it fails with this error:
`[ 37%] Built target artik-sdk-mqtt
[ 37%] Linking CXX shared library ../../../Release/armv7l/lib/libartik-sdk-bluetooth.so
cd /root/artik-sdk/build-armhf/package/src/build/src/modules/bluetooth && /usr/bin/cmake -E cmake_link_script CMakeFiles/artik-sdk-bluetooth.dir/link.txt --verbose=1
/usr/bin/g++  --sysroot="" -fPIC -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -std=c++0x -O3 -DNDEBUG -DCONFIG_RELEASE  -Wl,-Bsymbolic-functions -Wl,-z,relro -shared -Wl,-soname,libartik-sdk-bluetooth.so.1 -o ../../../Release/armv7l/lib/libartik-sdk-bluetooth.so.1.8.2 CMakeFiles/artik-sdk-bluetooth.dir/artik_bluetooth.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/a2dp.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/avrcp.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/adapter.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/agent.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/advertisement.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/bt.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/core.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/device.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/gatt.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/gatt_client.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/gatt_server.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/helper.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/pan.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/spp.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/ftp.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/assigned_numbers.c.o CMakeFiles/artik-sdk-bluetooth.dir/linux/linux_bluetooth.c.o CMakeFiles/artik-sdk-bluetooth.dir/cpp/artik_bluetooth.cpp.o  -L/root/artik-sdk/build-armhf/package/src/build/Release/armv7l/lib ../../../Release/armv7l/lib/libartik-sdk-base.so.1.8.2 -lglib-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -ldl -lssl -lcrypto 
cd /root/artik-sdk/build-armhf/package/src/build/src/modules/bluetooth && /usr/bin/cmake -E cmake_symlink_library ../../../Release/armv7l/lib/libartik-sdk-bluetooth.so.1.8.2 ../../../Release/armv7l/lib/libartik-sdk-bluetooth.so.1 ../../../Release/armv7l/lib/libartik-sdk-bluetooth.so
make[3]: Leaving directory '/root/artik-sdk/build-armhf/package/src/build'
[ 37%] Built target artik-sdk-bluetooth
make[2]: Leaving directory '/root/artik-sdk/build-armhf/package/src/build'
Makefile:130: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/artik-sdk/build-armhf/package/src/build'
dh_auto_build: make -j4 returned exit code 2
debian/rules:12: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
`

**Comment by glemercier** [comment]
The error details don't show in the log above, you need to scroll up to figure out the actual reason of the failure.

**Comment by mmajb** [comment]
Sorry. That's the error I think:

[ 32%] Linking CXX shared library ../../../Release/armv7l/lib/libartik-sdk-lwm2m.so
cd /root/artik-sdk/build-armhf/package/src/build/src/modules/lwm2m && /usr/bin/cmake -E cmake_link_script CMakeFiles/artik-sdk-lwm2m.dir/link.txt --verbose=1
/usr/bin/g++  --sysroot="" -fPIC -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -std=c++0x -O3 -DNDEBUG -DCONFIG_RELEASE  -Wl,-Bsymbolic-functions -Wl,-z,relro -shared -Wl,-soname,libartik-sdk-lwm2m.so.1 -o ../../../Release/armv7l/lib/libartik-sdk-lwm2m.so.1.8.2 CMakeFiles/artik-sdk-lwm2m.dir/artik_lwm2m.c.o CMakeFiles/artik-sdk-lwm2m.dir/linux_lwm2m.c.o CMakeFiles/artik-sdk-lwm2m.dir/cpp/artik_lwm2m.cpp.o  -L/root/artik-sdk/build-armhf/package/src/build/Release/armv7l/lib ../../../Release/armv7l/lib/libartik-sdk-base.so.1.8.2 -lwakaama-client -lglib-2.0 -ldl -lssl -lcrypto 
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/5/../../../arm-linux-gnueabihf/libwakaama-client.a(lwm2mclient.c.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/arm-linux-gnueabihf/5/../../../arm-linux-gnueabihf/libwakaama-client.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/modules/lwm2m/CMakeFiles/artik-sdk-lwm2m.dir/build.make:154: recipe for target 'Release/armv7l/lib/libartik-sdk-lwm2m.so.1.8.2' failed
make[3]: *** [Release/armv7l/lib/libartik-sdk-lwm2m.so.1.8.2] Error 1
make[3]: Leaving directory '/root/artik-sdk/build-armhf/package/src/build'
CMakeFiles/Makefile2:663: recipe for target 'src/modules/lwm2m/CMakeFiles/artik-sdk-lwm2m.dir/all' failed
make[2]: *** [src/modules/lwm2m/CMakeFiles/artik-sdk-lwm2m.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....

**Comment by glemercier** [comment]
What happens if you do:
```
$ ls -la /usr/lib/arm-linux-gnueabihf/libwakaama-client*
-rw-r--r-- 1 root root 128788 Jan 23 12:46 /usr/lib/arm-linux-gnueabihf/libwakaama-client.a
lrwxrwxrwx 1 root root     22 Apr 29  2016 /usr/lib/arm-linux-gnueabihf/libwakaama-client.so -> libwakaama-client.so.1
lrwxrwxrwx 1 root root     26 Apr 29  2016 /usr/lib/arm-linux-gnueabihf/libwakaama-client.so.1 -> libwakaama-client.so.1.5.0
-rw-r--r-- 1 root root  63304 Jan 23 12:46 /usr/lib/arm-linux-gnueabihf/libwakaama-client.so.1.5.0
$ md5sum /usr/lib/arm-linux-gnueabihf/libwakaama-client.so.1.5.0
de176a52fc5c1fc3850657d01e39587e  /usr/lib/arm-linux-gnueabihf/libwakaama-client.so.1.5.0
```
If this does not look as above, try checking if this package is installed:
`$ apt install wakaama-client-dev`

**Comment by glemercier** [comment]
have you done "apt update" first? The latest version of wakaama-client on the repo should be 1.5-0.

**Comment by mmajb** [comment]
Yes I have done that. I've tried removing the package and installing it again. But somehow the libwakaama-client.so files are not getting installed. Only the libwakaama-client.a gets installed.

**Comment by glemercier** [comment]
It really seems like you're not up-to-date with the repo. If the command "apt show wakaama-client-dev" does not show the same results than above, then something went wrong when you did "apt update".

**Comment by mmajb** [comment]
I tried on another Artik and the same thing happened. Only the libwakaama-client.a file gets installed. Running the command `apt show wakaama-client-dev` gives the following result:

`Package: wakaama-client-dev
Version: 1.5-0
Priority: optional
Section: libs
Source: wakaama-client
Maintainer: Gregory Lemercier <g.lemercier@samsung.com>
Installed-Size: 172 kB
Depends: wakaama-client
Homepage: https://github.com/obgm/wakaama
Download-Size: 55.2 kB
APT-Manual-Installed: yes
APT-Sources: http://repo.artik.cloud/artik/bin/pub/artik/ubuntu xenial/main armhf Packages
Description: Development files for implementation of the Open Mobile Alliance's LightWeight M2M protocol (LWM2M)

N: There are 3 additional records. Please use the '-a' switch to see them.`

**Comment by glemercier** [comment]
You should also make sure **wakaama-client** is installed as well, but it should be installed automatically by dependencies. Here is the content of each package:
```
[root@artik artik-sdk]# dpkg -L wakaama-client-dev
/.
/usr
/usr/include
/usr/include/arm-linux-gnueabihf
/usr/include/arm-linux-gnueabihf/lwm2mclient.h
/usr/lib
/usr/lib/arm-linux-gnueabihf
/usr/lib/arm-linux-gnueabihf/libwakaama-client.a
/usr/share
/usr/share/doc
/usr/share/doc/wakaama-client-dev
/usr/share/doc/wakaama-client-dev/copyright
/usr/share/doc/wakaama-client-dev/changelog.Debian.gz
[root@artik artik-sdk]# dpkg -L wakaama-client
/.
/usr
/usr/lib
/usr/lib/arm-linux-gnueabihf
/usr/lib/arm-linux-gnueabihf/libwakaama-client.so.1.5.0
/usr/share
/usr/share/doc
/usr/share/doc/wakaama-client
/usr/share/doc/wakaama-client/copyright
/usr/share/doc/wakaama-client/changelog.Debian.gz
/usr/lib/arm-linux-gnueabihf/libwakaama-client.so
/usr/lib/arm-linux-gnueabihf/libwakaama-client.so.1
```

**Comment by mmajb** [comment]
Ok so the wakaama-client version is old (1.4-0). However When I try to install the new version, it says that enmd is going to be uninstalled. Why is that? I need enmd for my application.

**Comment by mmajb** [comment]
Running the command `apt show enmd` returns this:

Package: enmd
Version: 1.5.4-1
Priority: optional
Section: admin
Maintainer: Vaibhav Singh <vaibhav1.s@samsung.com>
Installed-Size: 8489 kB
Depends: libcurl3, libarchive13, libwebsockets7, artiksee, libssl1.0.0, wakaama-client (= 1.4)
Download-Size: 2808 kB
APT-Manual-Installed: yes
APT-Sources: http://repo.artik.cloud/artik/bin/pub/artik/ubuntu xenial/main armhf Packages
Description: Service for managing constrained connected devices (Edge Nodes)

**Comment by glemercier** [comment]
Ok that's the reason. The version of the ENM you use is dependent on wakaama-client 1.4 and therefore prevents any new version from being installed.
It leaves you with the following choice:

1. Wait for the next version of the ENM to be released in the upcoming weeks, it updated its dependencies to wakaama-client 1.5
2. Keep curent ENM and downgrade the ARTIK SDK to version 1.7. I backported the MQTT patch in branch https://github.com/SamsungARTIK/artik-sdk/tree/1.7-maintenance therefore you could build from it

**Comment by mmajb** [comment]
By switching to version 1.7 the `./builddeb.sh armhf` process has completed successfully. But this version is not suitable for my application as I'm designing the application in C++ so I'll stick with the new SDK. When can I expect the release of the new version of ENM?

Thanks for the help.

**Comment by mmajb** [comment]
Also can you tell the expected release date of the SDK version 1.8.2?

Ahsan

**Comment by glemercier** [comment]
Can you detail which APIs are missing on SDK 1.7? I was not aware of any gap there.
SDK 1.8.2 will be out shortly, ENM won't be before a couple weeks.

**Comment by mmajb** [comment]
It didn't have the artik_module.hh file. Then in the artik_cloud.hh module, the Cloud class doesn't have the asynchronous functions that I'm using like `send_message_async`.

**Comment by mmajb** [comment]
Hi glemercier,

Thanks for the update. Another thing that I wanted to ask was that in the MQTT example, the CA certificate is hard-coded. Is there a way to obtain a certificate instead of hard-coding it? Thanks.

Ahsan

**Comment by glemercier** [comment]
The CA is hard-coded intentionally for security purposes. The MQTT connection will only succeed if the certifcate sent by the server can be verified against the hard-coded root CA certificate, in order to prevent Man In The Middle attacks. The root CA certificate of one websocket server is not supposed to change frequently, and prior notice should be made by the server maintainer anyway.

Note that you can set several trusted root CAs in the certificate string by appending the PEM data of the certificates together. This allows for keeping the client working during periods where the server certificate is changed, by having both the old and new certificates trusted.

**Comment by glemercier** [comment]
FYI, ENM v1.6.6-4 has been released and can downloaded from the package repository using 'apt'. This should fix the dependency issue you had having both the ENM and SDK v1.8 installed.

**Comment by mmajb** [comment]
Hi glemercier,
I'm using the latest SDK (v1.8.2) now but I'm still getting uninformed MQTT disconnections at random intervals. I've kept a keepalive interval of 60s and most of the times the MQTT connection stays stable, but every once in a while the Artik 5 would stop getting actions from all of the cloud devices that it has subscribed to. Previously, this would happen if there was no activity for at least 5 minutes but now it happens at random times. Can you please look into it? Thanks.

Ahsan
